FROM debian:buster-slim

WORKDIR /tester

COPY . .

# Upgrade the system and install dependencies for PostgreSQL
RUN apt-get update; \
  apt-get install -y \
  curl\
  nodejs-current \
  npm;

# Install newman
RUN npm install -g newman