@startuml Data flow
!theme crt-amber

' Define
actor Client
participant "Middleware\n/middleware/*" as Middleware
participant "Controller\n/[domain]/api.rs" as Controller
participant "Service\n/[domain]/service.rs" as Service
database DB

' client->server
Client -> Middleware: request
Middleware -> Controller
activate Controller #FFB000
Controller -> Controller: Assign to Request Object\n(/[domain]/request.rs)
Controller -> Service
Service -> DB


' server->client
Service <-- DB
Controller <-- Service
Controller --> Controller: Convert into Response Object\n(/[domain]/response.rs)
Client <-- Controller: response
deactivate Controller
@enduml